"""Short hover help text for charts (simple English)."""

HELP = {
    "dbu_usage": "Daily Databricks Units (DBU) used. More DBU means higher cost.",
    "product_mix": "Share of DBU by Databricks product (Jobs, SQL, All-Purpose, etc.).",
    "top_audit_services": "Services with the most audit events. Helps spot busy or risky areas.",
    "job_run_status": "Job runs grouped by result: succeeded, failed, or canceled.",
    "daily_dbu_trend": "DBU used each day in the selected period.",
    "dbu_by_product": "Daily DBU split by product. Shows which product drives spend.",
    "top_skus": "Top billing SKUs by DBU. Useful to find expensive line items.",
    "usage_type_mix": "DBU split by usage type (compute, storage, etc.).",
    "dbu_by_team": "DBU tagged per team. Shows who consumes the most.",
    "dbu_by_env": "DBU split by environment tag (dev, prod, etc.).",
    "monthly_dbu": "Total DBU per month. Good for month-over-month trends.",
    "dbu_by_sku": "DBU per SKU for the selected period.",
    "storage_networking": "DBU for storage and networking only (not compute).",
    "top_clusters": "Clusters with the highest DBU spend.",
    "top_jobs": "Jobs with the highest DBU spend.",
    "top_warehouses": "SQL warehouses with the highest DBU spend.",
    "top_users": "Users (run_as) with the highest DBU spend.",
    "weekend_cluster_dbu": "DBU on weekends (Sat/Sun). High values may mean idle clusters.",
    "query_spill": "Queries that wrote a lot of data to disk (spill). Often means not enough memory.",
    "avg_cpu": "Average CPU use per cluster. Low values may mean oversized clusters.",
    "avg_memory": "Average memory use per cluster. Low values may mean waste.",
    "top_failed_jobs": "Jobs with the most failed, timed out, or canceled runs.",
    "warehouse_event_types": "SQL warehouse events (scale up, scale down, start, stop).",
    "warehouse_event_timeline": "Warehouse events per day. Shows scaling activity over time.",
    "audit_daily": "Number of audit events per day.",
    "denied_by_service": "403 (access denied) events per service.",
    "uc_actions": "Unity Catalog actions (create, grant, delete, etc.).",
    "secrets_tokens": "Events about secrets, tokens, and IAM.",
    "login_by_ip": "Logins using a token, grouped by source IP.",
    "top_actors": "Users with the most audit actions.",
    "audit_heatmap": "Audit activity by service and date. Darker = more events.",
    "clusters_by_team": "Number of clusters per team tag.",
    "data_security_mode": "Clusters split by data security mode.",
    "cluster_source": "How clusters were created (UI, API, job, etc.).",
    "dbr_by_workspace": "Databricks Runtime (DBR) versions per workspace.",
    "node_types": "Driver node types used by clusters.",
    "runs_per_day": "Job runs per day in the selected period.",
    "success_rate": "Success rate per job. Lower bars need attention first.",
    "job_durations": "Average run, queue, and execution time per job (seconds).",
    "tasks_hierarchy": "Tasks split by type and result status.",
    "runs_by_team": "Job runs per team tag, colored by result.",
    "daily_latency": "Average SQL query time per day (milliseconds).",
    "warehouse_queue": "Average time queries waited for warehouse capacity.",
    "queries_by_user": "Number of SQL queries per user.",
    "latency_by_user": "Average query time per user.",
    "statements_by_type": "SQL statements by type and status.",
    "queries_by_warehouse": "Query count per SQL warehouse.",
    "cache_rate": "Daily share of queries served from result cache (%).",
}
