"""Short hover help text - simple English for the whole app."""

from __future__ import annotations

import html


def info_tip_html(help_text: str) -> str:
    return (
        f'<span class="chart-info-tip" tabindex="0">'
        f'<span class="chart-info-icon">ⓘ</span>'
        f'<span class="chart-info-popup">{html.escape(help_text)}</span>'
        f"</span>"
    )


HELP = {
    # ── Categories (main page headers) ──
    "cat_home": "Shows a quick view of cost, SQL, security, jobs, and compute. Use it to assess the current operating picture.",
    "cat_finops": "Shows DBU usage, costs, and top spenders. Use it to understand consumption and financial trends.",
    "cat_help": "Shows the app overview, dashboards, data sources, glossary, and support guidance.",
    "cat_optimization": "Shows waste signals, SQL performance, job reliability, and optimization opportunities.",
    "cat_security": "Shows audit activity, access events, Unity Catalog actions, and token usage.",
    "cat_compute": "Shows cluster inventory, runtime versions, tags, and cluster activity.",
    "cat_jobs": "Shows job volume, success rates, durations, tasks, and team usage.",
    "cat_sql": "Shows query performance, queue time, cache activity, spill, and warehouse usage.",
    "cat_platform": "Shows API inventory, ingestion activity, and driver log samples.",

    # ── Sidebar filters ──
    "filter_period_from": "Shows the first date included in the selected analysis.",
    "filter_period_to": "Shows the last date included in the selected analysis.",
    "filter_catalog": "Shows the Unity Catalog used for Databricks system tables.",
    "filter_trigramme": "Shows the workspace code used to narrow the view.",
    "filter_environment": "Shows the environment tag used to filter results.",
    "filter_nav": "Shows the dashboard sections and helps you move between them.",

    # ── Section headers (category pages) ──
    "sec_finops_summary": "Shows monthly DBU totals and daily trends. Use it to track spending patterns.",
    "sec_finops_top_spenders": "Shows the biggest DBU consumers by cluster, job, warehouse, and user.",
    "sec_finops_trends": "Shows daily DBU usage by Databricks product. Use it to understand product mix.",
    "sec_finops_team": "Shows DBU by team, cost center, and environment. Use it to improve ownership and governance.",
    "sec_finops_monthly": "Shows DBU totals by month. Use it to review longer-term trends.",
    "sec_finops_sku": "Shows top billing SKUs and usage types. Use it to review cost composition.",
    "sec_finops_storage": "Shows DBU for storage and networking. Use it to review non-compute consumption.",
    "sec_finops_prices": "Shows DBU usage alongside list prices. Use it to compare usage with pricing metadata.",

    "sec_opt_action": "Shows recommended actions based on workspace signals. Use it to prioritize next steps.",
    "sec_opt_weekend": "Shows clusters that ran on weekends. Use it to review potential idle usage.",
    "sec_opt_failed_jobs": "Shows job runs that ended with failures or timeouts. Use it to review reliability.",
    "sec_opt_slow_sql": "Shows the slowest finished SQL queries. Use it to review performance opportunities.",
    "sec_opt_spill": "Shows queries with disk spill. Use it to detect memory pressure and tuning opportunities.",
    "sec_opt_autostop": "Shows clusters and their auto-stop settings. Use it to review idle cost controls.",
    "sec_opt_node_usage": "Shows average CPU and memory usage per cluster. Use it to review utilization patterns.",
    "sec_opt_warehouse": "Shows SQL warehouse scale events. Use it to review capacity behavior.",

    "sec_sec_audit": "Shows audit activity over time. Use it to review platform events and usage patterns.",
    "sec_sec_denied": "Shows access-denied events. Use it to review permission and governance activity.",
    "sec_sec_top_users": "Shows the users with the most audit activity. Use it to review engagement patterns.",
    "sec_sec_heatmap": "Shows audit activity by service and day. Use it to spot busy periods.",
    "sec_sec_uc": "Shows Unity Catalog actions. Use it to review governance and data access activity.",
    "sec_sec_secrets": "Shows secret, token, and IAM activity. Use it to review security operations.",
    "sec_sec_signin": "Shows token sign-ins and client IPs. Use it to review authentication activity.",

    "sec_compute_list": "Shows the full cluster inventory. Use it to review the current compute fleet.",
    "sec_compute_tags": "Shows team tags, security mode, and cluster creation source. Use it to review governance context.",
    "sec_compute_runtime": "Shows DBR versions and node types in use. Use it to review runtime standards.",
    "sec_compute_events": "Shows cluster lifecycle events. Use it to review operational activity.",

    "sec_jobs_overview": "Shows daily job volume and run outcomes. Use it to review workload trends.",
    "sec_jobs_success": "Shows success rate by job. Use it to compare workflow reliability.",
    "sec_jobs_duration": "Shows average run, queue, and execution times. Use it to review job efficiency.",
    "sec_jobs_team": "Shows job runs by team and outcome. Use it to review workload ownership.",
    "sec_jobs_tasks": "Shows tasks inside jobs by type and result. Use it to review workflow composition.",

    "sec_sql_perf": "Shows query counts, latency, and failures. Use it to review SQL health.",
    "sec_sql_queues": "Shows time spent waiting for warehouse capacity. Use it to review SQL throughput.",
    "sec_sql_cache": "Shows cache use and spill activity. Use it to review query efficiency.",
    "sec_sql_user": "Shows SQL load and latency by user. Use it to review usage patterns.",
    "sec_sql_warehouses": "Shows query volume and warehouse settings. Use it to review warehouse usage.",
    "sec_sql_statements": "Shows SQL statement types and outcomes. Use it to review workload patterns.",

    "sec_platform_api": "Shows live counts from the Databricks API. Use it to review platform inventory.",
    "sec_platform_ingestion": "Shows ingestion pipeline activity. Use it to review data pipeline health.",
    "sec_platform_logs": "Shows sampled driver logs. Use it to review log-based troubleshooting context.",

    "sec_summary": "Shows the key numbers for the selected category. Use it to focus on the most important signals.",
    "sec_help_about": "Shows what the app does and who it is designed for. Use it to understand the purpose of the solution.",
    "sec_help_dashboards": "Shows what each dashboard is intended to cover. Use it to choose the right view.",
    "sec_help_sources": "Shows the Databricks and optional sources used by the app. Use it to review data coverage.",
    "sec_help_requirements": "Shows the access and configuration needed for each page. Use it to prepare the environment.",
    "sec_help_glossary": "Shows simple definitions for the main terms used in the app. Use it to support onboarding.",
    "sec_help_signals": "Shows how to interpret common signals and trends. Use it to read the dashboards with context.",
    "sec_help_limitations": "Shows the app’s enterprise readiness notes. Use it to understand the solution context.",
    "sec_help_troubleshooting": "Shows common guidance for empty or unexpected views. Use it to resolve data issues quickly.",
    "sec_help_safe_usage": "Shows safe usage guidance for governance and observability. Use it to support secure adoption.",

    "sec_home_kpis": "Shows DBU, SQL activity, audit events, failed jobs, clusters, and warehouses. Use it to assess the current state.",
    "sec_home_cost": "Shows daily DBU usage and product mix. Use it to understand which products drive consumption.",
    "sec_home_activity": "Shows top audit services and job outcomes. Use it to review operational activity.",

    # ── Charts ──
    "dbu_usage": "Shows daily DBU usage. Use it to understand consumption trends over time.",
    "product_mix": "Shows DBU by Databricks product. Use it to understand where spend is concentrated.",
    "top_audit_services": "Shows the services with the most audit activity. Use it to review active areas.",
    "job_run_status": "Shows job runs by status. Use it to review workflow outcomes.",
    "daily_dbu_trend": "Shows daily DBU usage. Use it to review day-to-day consumption.",
    "dbu_by_product": "Shows DBU by product. Use it to understand which products drive spend.",
    "top_skus": "Shows the biggest billing SKUs by DBU. Use it to review cost drivers.",
    "usage_type_mix": "Shows DBU by usage type. Use it to review spend categories.",
    "dbu_by_team": "Shows DBU by team. Use it to review ownership and responsibility.",
    "dbu_by_env": "Shows DBU by environment. Use it to review environment-level consumption.",
    "monthly_dbu": "Shows DBU totals by month. Use it to review long-range trends.",
    "dbu_by_sku": "Shows DBU by SKU. Use it to review pricing and usage patterns.",
    "storage_networking": "Shows storage and networking DBU. Use it to review non-compute consumption.",
    "top_clusters": "Shows the clusters with the highest DBU consumption. Use it to find major spend drivers.",
    "top_jobs": "Shows jobs with the highest DBU consumption. Use it to review top workload drivers.",
    "top_warehouses": "Shows warehouses with the highest DBU consumption. Use it to review top SQL workloads.",
    "top_users": "Shows users with the highest DBU consumption. Use it to review major usage contributors.",
    "weekend_cluster_dbu": "Shows DBU used on weekends. Use it to review compute patterns outside business hours.",
    "query_spill": "Shows queries with disk spill. Use it to detect memory pressure or tuning opportunities.",
    "avg_cpu": "Shows average CPU usage per cluster. Use it to identify clusters that may be optimized or resized.",
    "avg_memory": "Shows average memory usage per cluster. Use it to review utilization patterns.",
    "top_failed_jobs": "Shows jobs with the most failed runs. Use it to review workflow reliability.",
    "warehouse_event_types": "Shows warehouse event types. Use it to review scaling and availability activity.",
    "warehouse_event_timeline": "Shows warehouse events over time. Use it to review capacity changes.",
    "cluster_events_daily": "Shows cluster lifecycle events per day. Use it to review operational activity.",
    "audit_daily": "Shows audit events per day. Use it to review activity trends.",
    "denied_by_service": "Shows denied access events by service. Use it to review permission activity.",
    "uc_actions": "Shows Unity Catalog actions. Use it to review governance activity.",
    "secrets_tokens": "Shows secret, token, and IAM activity. Use it to review security operations.",
    "login_by_ip": "Shows token sign-ins by source IP. Use it to review authentication patterns.",
    "top_actors": "Shows the users with the most audit actions. Use it to review activity distribution.",
    "audit_heatmap": "Shows audit activity by service and date. Use it to review daily patterns.",
    "clusters_by_team": "Shows clusters by team tag. Use it to review ownership and distribution.",
    "data_security_mode": "Shows clusters by data security mode. Use it to review environment posture.",
    "cluster_source": "Shows how clusters were created. Use it to review provisioning patterns.",
    "dbr_by_workspace": "Shows DBR versions by workspace. Use it to review runtime standards.",
    "node_types": "Shows the node types used by clusters. Use it to review compute profiles.",
    "runs_per_day": "Shows job runs per day. Use it to review workload volume over time.",
    "success_rate": "Shows success rate by job. Use it to compare workflow reliability.",
    "job_durations": "Shows average job timing metrics. Use it to review execution efficiency.",
    "tasks_hierarchy": "Shows tasks by type and result. Use it to review workflow composition.",
    "runs_by_team": "Shows job runs by team and status. Use it to review team activity.",
    "daily_latency": "Shows average SQL latency per day. Use it to review query performance trends.",
    "warehouse_queue": "Shows average queue time for SQL workloads. Use it to review warehouse capacity.",
    "queries_by_user": "Shows SQL query volume by user. Use it to review workload distribution.",
    "latency_by_user": "Shows average query latency by user. Use it to review user-level performance.",
    "statements_by_type": "Shows SQL statements by type and status. Use it to review query patterns.",
    "queries_by_warehouse": "Shows query volume by warehouse. Use it to review warehouse usage.",
    "cache_rate": "Shows the daily cache hit rate. Use it to review query efficiency.",

    # ── KPI metrics (metrics_row & inline) ──
    "kpi_dbu_month": "Shows the current month’s DBU total. Use it to track monthly consumption.",
    "kpi_dbu_last_month": "Shows the previous month’s DBU total. Use it to compare monthly trends.",
    "kpi_savings_est": "Shows a simple savings estimate. Use it to review optimization potential.",
    "kpi_job_runs": "Shows the total number of job runs. Use it to review workload volume.",
    "kpi_job_success": "Shows runs that completed successfully. Use it to track job reliability.",
    "kpi_job_failed": "Shows runs that ended in failure. Use it to review operational exceptions.",
    "kpi_job_avg_duration": "Shows the average job duration. Use it to review execution time.",
    "kpi_audit_events": "Shows audit events in the selected period. Use it to review activity levels.",
    "kpi_audit_users": "Shows distinct users seen in audit logs. Use it to review participation.",
    "kpi_audit_errors": "Shows audit events with error status codes. Use it to review incident activity.",
    "kpi_sql_queries": "Shows SQL statements executed in the selected period. Use it to review workload activity.",
    "kpi_sql_avg_latency": "Shows the average query duration. Use it to review typical SQL response time.",
    "kpi_sql_p95": "Shows the 95th percentile query time. Use it to review slow outlier queries.",
    "kpi_sql_failed": "Shows failed SQL queries. Use it to review execution quality.",
    "kpi_cache_total": "Shows all SQL queries in the period. Use it to review query volume.",
    "kpi_cache_hits": "Shows queries answered from result cache. Use it to review cache efficiency.",
    "kpi_cache_spill": "Shows queries that spilled data to disk. Use it to review memory pressure.",
    "kpi_clusters_total": "Shows the current cluster inventory. Use it to review compute scale.",
    "kpi_clusters_photon": "Shows clusters using Photon. Use it to review acceleration adoption.",
    "kpi_clusters_single": "Shows single-node clusters. Use it to review lightweight compute usage.",
    "kpi_autostop_total": "Shows all clusters in the inventory. Use it to review the compute fleet.",
    "kpi_autostop_none": "Shows clusters with no auto-stop setting. Use it to review idle-cost controls.",
    "kpi_autostop_short": "Shows clusters with short auto-stop settings. Use it to review cost guardrails.",
    "kpi_api_clusters": "Shows clusters returned by the live API. Use it to review current inventory.",
    "kpi_api_warehouses": "Shows warehouses returned by the live API. Use it to review current SQL inventory.",
    "kpi_api_jobs": "Shows jobs returned by the live API. Use it to review current workflows.",
    "kpi_ingestion_rows": "Shows the number of ingestion rows. Use it to review pipeline volume.",
    "kpi_ingestion_cols": "Shows ingestion log columns. Use it to review data structure richness.",
    "kpi_log_warnings": "Shows log lines with warnings or errors. Use it to review operational issues.",

    # ── Data tables ──
    "tbl_weekend_clusters": "Shows weekend clusters with their auto-stop settings. Use it to review compute usage patterns.",
    "tbl_slow_sql": "Shows the slowest queries with context. Use it to review performance candidates.",
    "tbl_spill_queries": "Shows queries with high spill volume. Use it to review memory-heavy workloads.",
    "tbl_autostop": "Shows cluster auto-stop settings. Use it to review cost-control behavior.",
    "tbl_job_failures": "Shows job run results by job and status. Use it to review reliability patterns.",
    "tbl_team_attribution": "Shows DBU details by team, cost center, and environment. Use it to review chargeback context.",
    "tbl_monthly_dbu": "Shows monthly DBU totals. Use it to review longer-term trends.",
    "tbl_list_prices": "Shows Databricks list prices by SKU. Use it to review pricing metadata.",
    "tbl_job_success": "Shows run counts and success rates by job. Use it to review workflow quality.",
    "tbl_job_tasks": "Shows task counts by type and result. Use it to review workflow structure.",
    "tbl_denied_events": "Shows recent denied access events. Use it to review permission activity.",
    "tbl_uc_recent": "Shows recent Unity Catalog events. Use it to review governance movements.",
    "tbl_secrets_events": "Shows recent secret, token, and IAM events. Use it to review security context.",
    "tbl_user_agents": "Shows the most common user agents in audit logs. Use it to review client patterns.",
    "tbl_top_actors": "Shows the most active users in audit logs. Use it to review participation patterns.",
    "tbl_queue_waits": "Shows queries with long queue waits. Use it to review warehouse contention.",
    "tbl_warehouses": "Shows warehouse size, state, and serverless setting. Use it to review SQL compute settings.",
    "tbl_cluster_list": "Shows the full cluster inventory with key settings. Use it to review compute resources.",
    "tbl_cluster_events": "Shows raw cluster events. Use it to review operational activity.",
    "tbl_api_clusters": "Shows cluster objects from the API response. Use it to review live inventory.",
    "tbl_api_warehouses": "Shows warehouse objects from the API response. Use it to review live SQL inventory.",
    "tbl_api_jobs": "Shows job names and IDs from the API response. Use it to review live workflows.",
    "tbl_ingestion_log": "Shows the latest ingestion log entries. Use it to review pipeline activity.",
    "tbl_action_plan": "Shows recommended actions with supporting signals. Use it to review next steps.",
    "tbl_log_file": "Shows the available driver log files. Use it to choose a log to review.",

    # ── Page context ──
    "ctx_period": "Shows the active date range for the dashboards. Change it in the sidebar.",
    "ctx_refresh": "Shows the data refresh action. Use it to reload the latest dashboard data.",
}

CAT_HELP = {
    "Home": HELP["cat_home"],
    "FinOps": HELP["cat_finops"],
    "Optimization": HELP["cat_optimization"],
    "Security": HELP["cat_security"],
    "Compute": HELP["cat_compute"],
    "Jobs": HELP["cat_jobs"],
    "SQL": HELP["cat_sql"],
    "Platform": HELP["cat_platform"],
}
