"""Short hover help text — simple English for the whole app."""

from __future__ import annotations

import html


def info_tip_html(help_text: str) -> str:
    return (
        f'<span class="chart-info-tip" tabindex="0">'
        f'<span class="chart-info-icon">ⓘ</span>'
        f'<span class="chart-info-popup">{html.escape(help_text)}</span>'
        f"</span>"
    )


HELP = {
    # ── Categories (main page headers) ──
    "cat_home": "Shows a quick view of cost, SQL, security, jobs, and compute. Use it to assess the current operating picture.",
    "cat_finops": "Shows DBU usage, costs, and top spenders. Use it to understand consumption and financial trends.",
    "cat_help": "Shows the app overview, dashboards, data sources, glossary, and support guidance.",
    "cat_optimization": "Shows waste signals, SQL performance, job reliability, and optimization opportunities.",
    "cat_security": "Shows audit activity, access events, Unity Catalog actions, and token usage.",
    "cat_compute": "Shows cluster inventory, runtime versions, tags, and cluster activity.",
    "cat_jobs": "Shows job volume, success rates, durations, tasks, and team usage.",
    "cat_sql": "Shows query performance, queue time, cache activity, spill, and warehouse usage.",
    "cat_platform": "Shows API inventory, ingestion activity, and driver log samples.",

    # ── Sidebar filters ──
    "filter_catalog": "Shows the Unity Catalog used for Databricks system tables.",
    "filter_trigramme": "Shows the workspace code used to narrow the view.",
    "filter_environment": "Shows the environment tag used to filter results.",
    "filter_nav": "Shows the dashboard sections and helps you move between them.",

    # ── Section headers (category pages) ──
    "sec_finops_summary": "Shows monthly DBU totals and daily trends. Use it to track spending patterns.",
    "sec_finops_top_spenders": "Shows the biggest DBU consumers by cluster, job, warehouse, and user.",
    "sec_finops_trends": "Shows daily DBU usage by Databricks product. Use it to understand product mix.",
    "sec_finops_team": "Shows DBU by team, cost center, and environment. Use it to improve ownership and governance.",
    "sec_finops_monthly": "Shows DBU totals by month. Use it to review longer-term trends.",
    "sec_finops_sku": "Shows top billing SKUs and usage types. Use it to review cost composition.",
    "sec_finops_storage": "Shows DBU for storage and networking. Use it to review non-compute consumption.",
    "sec_finops_prices": "Shows DBU usage alongside list prices. Use it to compare usage with pricing metadata.",

    "sec_savings_scan": "Shows each waste rule with the cost in scope and a conservative monthly saving estimate.",
    "sec_savings_details": "Shows the exact clusters, jobs, and warehouses behind each saving, with the fix and a CSV export.",
    "cat_action_plan": "Every problem detected in your data — cost, governance, performance, reliability, security — with owner and fix.",
    "sec_action_plan": "All findings ranked by severity, then by money at stake.",
    "sec_home_actions": "The five most important findings. The full list is in Action plan.",

    "sec_opt_action": "Shows recommended actions based on workspace signals. Use it to prioritize next steps.",
    "sec_opt_weekend": "Shows clusters that ran on weekends. Use it to review potential idle usage.",
    "sec_opt_failed_jobs": "Shows job runs that ended with failures or timeouts. Use it to review reliability.",
    "sec_opt_slow_sql": "Shows the slowest finished SQL queries. Use it to review performance opportunities.",
    "sec_opt_spill": "Shows queries with disk spill. Use it to detect memory pressure and tuning opportunities.",
    "sec_opt_autostop": "Shows clusters and their auto-stop settings. Use it to review idle cost controls.",
    "sec_opt_node_usage": "Shows average CPU and memory usage per cluster. Use it to review utilization patterns.",
    "sec_opt_warehouse": "Shows SQL warehouse scale events. Use it to review capacity behavior.",

    "sec_sec_audit": "Shows audit activity over time. Use it to review platform events and usage patterns.",
    "sec_sec_denied": "Shows access-denied events. Use it to review permission and governance activity.",
    "sec_sec_top_users": "Shows the users with the most audit activity. Use it to review engagement patterns.",
    "sec_sec_heatmap": "Shows audit activity by service and day. Use it to spot busy periods.",
    "sec_sec_uc": "Shows Unity Catalog actions. Use it to review governance and data access activity.",
    "sec_sec_secrets": "Shows secret, token, and IAM activity. Use it to review security operations.",
    "sec_sec_signin": "Shows token sign-ins and client IPs. Use it to review authentication activity.",

    "sec_compute_list": "Shows the full cluster inventory. Use it to review the current compute fleet.",
    "sec_compute_tags": "Shows team tags, security mode, and cluster creation source. Use it to review governance context.",
    "sec_compute_runtime": "Shows DBR versions and node types in use. Use it to review runtime standards.",
    "sec_compute_events": "Shows cluster lifecycle events. Use it to review operational activity.",

    "sec_jobs_overview": "Shows daily job volume and run outcomes. Use it to review workload trends.",
    "sec_jobs_success": "Shows success rate by job. Use it to compare workflow reliability.",
    "sec_jobs_duration": "Shows average run, queue, and execution times. Use it to review job efficiency.",
    "sec_jobs_team": "Shows job runs by team and outcome. Use it to review workload ownership.",
    "sec_jobs_tasks": "Shows tasks inside jobs by type and result. Use it to review workflow composition.",

    "sec_sql_perf": "Shows query counts, latency, and failures. Use it to review SQL health.",
    "sec_sql_queues": "Shows time spent waiting for warehouse capacity. Use it to review SQL throughput.",
    "sec_sql_cache": "Shows cache use and spill activity. Use it to review query efficiency.",
    "sec_sql_user": "Shows SQL load and latency by user. Use it to review usage patterns.",
    "sec_sql_warehouses": "Shows query volume and warehouse settings. Use it to review warehouse usage.",
    "sec_sql_statements": "Shows SQL statement types and outcomes. Use it to review workload patterns.",

    "sec_platform_api": "Shows live counts from the Databricks API. Use it to review platform inventory.",
    "sec_platform_ingestion": "Shows ingestion pipeline activity. Use it to review data pipeline health.",
    "sec_platform_logs": "Shows sampled driver logs. Use it to review log-based troubleshooting context.",

    "sec_summary": "Shows the key numbers for the selected category. Use it to focus on the most important signals.",
    "sec_help_about": "Shows what the app does and who it is designed for. Use it to understand the purpose of the solution.",
    "sec_help_dashboards": "Shows what each dashboard is intended to cover. Use it to choose the right view.",
    "sec_help_sources": "Shows the Databricks and optional sources used by the app. Use it to review data coverage.",
    "sec_help_requirements": "Shows the access and configuration needed for each page. Use it to prepare the environment.",
    "sec_help_glossary": "Shows simple definitions for the main terms used in the app. Use it to support onboarding.",
    "sec_help_signals": "Shows how to interpret common signals and trends. Use it to read the dashboards with context.",
    "sec_help_limitations": "Shows the app’s enterprise readiness notes. Use it to understand the solution context.",
    "sec_help_troubleshooting": "Shows common guidance for empty or unexpected views. Use it to resolve data issues quickly.",
    "sec_help_safe_usage": "Shows safe usage guidance for governance and observability. Use it to support secure adoption.",

    "sec_home_kpis": "Shows DBU, SQL activity, audit events, failed jobs, clusters, and warehouses. Use it to assess the current state.",
    "sec_home_cost": "Shows daily DBU usage and product mix. Use it to understand which products drive consumption.",
    "sec_home_activity": "Shows top audit services and job outcomes. Use it to review operational activity.",

    # ── Charts ──
    "dbu_usage": "Cost per day. Spikes point to new or runaway workloads; weekdays should be higher than weekends.",
    "product_mix": "Share of cost by Databricks product. All-Purpose (interactive) is the priciest: keep it under ~30%.",
    "top_audit_services": "Services with the most audit events. The top ones are where your platform is most used.",
    "job_run_status": "Job runs by outcome. Anything other than SUCCEEDED is paid compute with no result.",
    "daily_dbu_trend": "Consumption per day. A steady climb without new projects usually means waste.",
    "dbu_by_product": "Consumption by product. All-Purpose (interactive) is the priciest per unit.",
    "top_skus": "The price lines (SKUs) that drive consumption. ALL_PURPOSE costs about 2x JOBS for the same work.",
    "usage_type_mix": "Consumption by usage type (compute, storage, network). Compute is normally the bulk.",
    "dbu_by_team": "Consumption per Team tag. '(not set)' is usage nobody owns: it should be close to zero.",
    "dbu_by_env": "Consumption per environment. Dev + UAT above ~30% of Prod is usually over-provisioned.",
    "monthly_dbu": "Consumption per month. Read the trend over 3+ months, not a single month.",
    "dbu_by_sku": "Consumption per SKU: which pricing lines your teams rely on.",
    "storage_networking": "Storage and network usage. It should grow slowly; a jump means duplicated data or egress.",
    "top_clusters": "The clusters that consume the most. Check auto-stop and size on the first ones.",
    "top_jobs": "The jobs that consume the most. Check their failure rate and cluster type first.",
    "top_warehouses": "The SQL warehouses that consume the most. Check size vs queue time and auto-stop.",
    "top_users": "The identities that consume the most. Service principals are expected; humans at the top deserve a look.",
    "weekend_cluster_dbu": "Clusters busy on Saturday/Sunday. Interactive ones here are usually left running.",
    "query_spill": "Queries that ran out of memory and spilled to disk. The top bars are the queries to rewrite first.",
    "avg_cpu": "Average CPU per cluster. Under 20% = oversized cluster: you pay for idle cores.",
    "avg_memory": "Average memory per cluster. Over 90% = undersized: expect spill and failures.",
    "top_failed_jobs": "Jobs with the most failed runs. The first bars are the bugs worth fixing first.",
    "warehouse_event_types": "Warehouse start, stop and scaling events. Many scale-ups = demand above the minimum size.",
    "warehouse_event_timeline": "Warehouse events per day. Frequent start/stop = bursty usage or a very short auto-stop.",
    "cluster_events_daily": "Cluster lifecycle events per day. Spikes = restarts or resizes to investigate.",
    "audit_daily": "Audit events per day. Spikes at night or on weekends deserve a look.",
    "denied_by_service": "Access-denied (403) events per service. Many on one service = missing grants there.",
    "uc_actions": "Unity Catalog actions. Grants and deletes should be rare and done by a few admins.",
    "secrets_tokens": "Secret, token and IAM events. Writes, deletes and role changes should be rare and expected.",
    "login_by_ip": "Sign-ins per source IP. Unknown IPs, or one identity from many IPs, = token risk.",
    "top_actors": "Identities with the most actions. Automation should run as service principals, not people.",
    "audit_heatmap": "Audit events by service and day. Dark cells on unusual days are worth a check.",
    "clusters_by_team": "Clusters per Team tag. '(not set)' = clusters with no owner for chargeback.",
    "data_security_mode": "Clusters by access mode. NONE (no isolation) bypasses Unity Catalog: it should be zero.",
    "cluster_source": "How clusters were created (UI, API, job). Many UI clusters = little standardization.",
    "dbr_by_workspace": "Runtime versions in use. Old versions miss security patches and speed-ups.",
    "node_types": "Node types in use. A short approved list is easier to govern.",
    "runs_per_day": "Job runs per day by outcome. The failed share should stay small and not grow.",
    "success_rate": "Success rate per job. A production job under 95% needs a fix.",
    "job_durations": "Average run, queue and execution time. A growing duration = growing data or degrading code.",
    "tasks_hierarchy": "Tasks by type and outcome. One type failing more than others points to a shared cause.",
    "runs_by_team": "Job runs per team and outcome: who owns the workload and the failures.",
    "daily_latency": "Average SQL query time per day. A rising line = slower dashboards for your users.",
    "warehouse_queue": "Average time queries wait for capacity. Over 10 s = the warehouse is saturated.",
    "queries_by_user": "SQL queries per user. One very high user is often a tool polling too often.",
    "latency_by_user": "Average query time per user. High values point to heavy or badly written queries.",
    "statements_by_type": "Statements by type and outcome. Many small INSERT/UPDATE = a row-by-row pattern to batch.",
    "queries_by_warehouse": "Queries per warehouse. Big warehouses with few queries are wasted money.",
    "cache_rate": "Share of queries answered from the result cache (free and instant). Higher is better.",

    # ── KPI metrics (metrics_row & inline) ──
    "kpi_dbu_month": "Shows the current month’s DBU total. Use it to track monthly consumption.",
    "kpi_dbu_last_month": "Shows the previous month’s DBU total. Use it to compare monthly trends.",
    "kpi_savings_est": "Shows a simple savings estimate. Use it to review optimization potential.",
    "kpi_job_runs": "Shows the total number of job runs. Use it to review workload volume.",
    "kpi_job_success": "Shows runs that completed successfully. Use it to track job reliability.",
    "kpi_job_failed": "Shows runs that ended in failure. Use it to review operational exceptions.",
    "kpi_job_avg_duration": "Shows the average job duration. Use it to review execution time.",
    "kpi_audit_events": "Shows audit events in the selected period. Use it to review activity levels.",
    "kpi_audit_users": "Shows distinct users seen in audit logs. Use it to review participation.",
    "kpi_audit_errors": "Shows audit events with error status codes. Use it to review incident activity.",
    "kpi_sql_queries": "Shows SQL statements executed in the selected period. Use it to review workload activity.",
    "kpi_sql_avg_latency": "Shows the average query duration. Use it to review typical SQL response time.",
    "kpi_sql_p95": "Shows the 95th percentile query time. Use it to review slow outlier queries.",
    "kpi_sql_failed": "Shows failed SQL queries. Use it to review execution quality.",
    "kpi_cache_total": "Shows all SQL queries in the period. Use it to review query volume.",
    "kpi_cache_hits": "Shows queries answered from result cache. Use it to review cache efficiency.",
    "kpi_cache_spill": "Shows queries that spilled data to disk. Use it to review memory pressure.",
    "kpi_clusters_total": "Shows the current cluster inventory. Use it to review compute scale.",
    "kpi_clusters_photon": "Shows clusters using Photon. Use it to review acceleration adoption.",
    "kpi_clusters_single": "Shows single-node clusters. Use it to review lightweight compute usage.",
    "kpi_autostop_total": "Shows all clusters in the inventory. Use it to review the compute fleet.",
    "kpi_autostop_none": "Shows clusters with no auto-stop setting. Use it to review idle-cost controls.",
    "kpi_autostop_short": "Shows clusters with short auto-stop settings. Use it to review cost guardrails.",
    "kpi_api_clusters": "Shows clusters returned by the live API. Use it to review current inventory.",
    "kpi_api_warehouses": "Shows warehouses returned by the live API. Use it to review current SQL inventory.",
    "kpi_api_jobs": "Shows jobs returned by the live API. Use it to review current workflows.",
    "kpi_ingestion_rows": "Shows the number of ingestion rows. Use it to review pipeline volume.",
    "kpi_ingestion_cols": "Shows ingestion log columns. Use it to review data structure richness.",
    "kpi_log_warnings": "Shows log lines with warnings or errors. Use it to review operational issues.",

    # ── Data tables ──
    "tbl_weekend_clusters": "Clusters used on weekends with their auto-stop. Auto-stop 0 or over 30 min = fix first.",
    "tbl_slow_sql": "The slowest queries and who ran them. Open them in Query history → Query profile.",
    "tbl_spill_queries": "Queries that spilled the most. Rewrite them or cluster the tables they read.",
    "tbl_autostop": "Auto-stop of every cluster. 0 = never stops; 10–30 min is the target.",
    "tbl_job_failures": "Runs per job and outcome. Repeated FAILED on the same job = a bug to fix.",
    "tbl_team_attribution": "Cost per team, cost center and environment. Export it for chargeback.",
    "tbl_monthly_dbu": "Totals per month, for reporting.",
    "tbl_list_prices": "The list price per SKU used for every cost in this app.",
    "tbl_job_success": "Runs and success rate per job. Sort by success rate to find the weakest jobs.",
    "tbl_job_tasks": "Task counts per type and outcome.",
    "tbl_denied_events": "Latest access-denied events. The same identity many times = missing grant or probing.",
    "tbl_uc_recent": "Latest Unity Catalog events. Check that grants and deletes were expected.",
    "tbl_secrets_events": "Latest secret, token and IAM events. Check every write, delete and role change.",
    "tbl_user_agents": "Most common clients. Unknown clients deserve a look.",
    "tbl_top_actors": "Most active identities.",
    "tbl_queue_waits": "Queries that waited longest for capacity, and on which warehouse.",
    "tbl_warehouses": "Size, state and type of every SQL warehouse.",
    "tbl_cluster_list": "Every interactive cluster with its key settings.",
    "tbl_cluster_events": "Raw cluster events, newest first.",
    "tbl_api_clusters": "Clusters returned by the live API.",
    "tbl_api_warehouses": "Warehouses returned by the live API.",
    "tbl_api_jobs": "Jobs returned by the live API.",
    "tbl_ingestion_log": "Latest ingestion log entries.",
    "tbl_action_plan": "Shows recommended actions with supporting signals. Use it to review next steps.",
    "tbl_log_file": "Driver log files available.",
}

CAT_HELP = {
    "Home": HELP["cat_home"],
    "Action plan": HELP["cat_action_plan"],
    "FinOps": HELP["cat_finops"],
    "Optimization": HELP["cat_optimization"],
    "Security": HELP["cat_security"],
    "Compute": HELP["cat_compute"],
    "Jobs": HELP["cat_jobs"],
    "SQL": HELP["cat_sql"],
    "Platform": HELP["cat_platform"],
}
